config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :movies, only: %i[show]
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6, message: "must be at least 6 characters long" }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks

    validates :title, presence: true
    validates :title, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    begin
      @list = List.find(params[:list_id])
      @bookmark = Bookmark.new
    rescue ActiveRecord::RecordNotFound
      # Si la liste n'est pas trouvée, rediriger vers une autre page avec un message d'erreur
      flash[:alert] = "La liste demandée n'a pas été trouvée."
      redirect_to root_path # Remplacez 'some_other_path' par le chemin de redirection souhaité
    end
  end
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :handle_not_found
  def index
    @lists = List.all
    @movies = Movie.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :created_at, :updated_at, :photo)
  end

  def handle_not_found
    redirect_to root_path, alert: "List not found"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
      @movies = Movie.all
      @list = List.all
      @bookmark = Bookmark.new
  end

  def show

    @movie = Movie.find(params[:id])
    
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<!-- app/views/bookmarks/new.html.erb -->

<h1>New Bookmark for <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.input :comment, label: 'Comment', input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.association :movie, collection: Movie.all, prompt: "Choose a movie", input_html: { class: 'form-control' } %>
  </div>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg);">
  <div class="container text-center">
    <h1>List of Movies <strong>Imerssion</strong> to <strong>Cinema</strong>!
      <strong> Take Pops Corns...</strong></h1>
  </div>
</div>


<div class="row mt-5">
  <% @movies.each do |movie| %>
    <div class="col-md-4 mb-3">
      <div class="card custom-card">
        <%= image_tag(movie.poster_url, alt: movie.title, class: "card-img-top") %>
        <div class="card-body custom-card-body">
          <h5 class="card-title"><%= movie.title %></h5>
          <p class="card-text"><%= movie.overview %></p>
        </div>
        <div class="card-footer">
          <%= link_to 'Details', movie_path(movie), class: "btn btn-primary rounded" %>
          <%= link_to 'Create Bookmark', new_list_path(movie), class: "btn btn-secondary rounded" %>
        </div>
      </div>
    </div>
  <% end %>
</div>



<% if @lists.present? %>
  <h1> <strong>List of Lists</strong></h1>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4 mb-3">
        <div class="card h-100 custom-card">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= list.name %></h5>
            <%= link_to 'View List', list_path(list), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/lists/new.html.erb
<div class="container">
  <h1>New List</h1>

  <%= simple_form_for @list do |f| %>
    <div class="form-group">
      <%= f.input :name, label: 'List Name', input_html: { class: 'form-control' } %>
     
      <%= f.input :photo, as: :file %>
    </div>

    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<%= link_to 'Retour à toutes les listes', lists_path, class: 'btn btn-secondary' %>
<div class="row mt-5">
  <% @list.movies.each do |movie| %>
    <div class="col-md-4 mb-3">
      <%= link_to movie_path(movie), class: "text-decoration-none" do %>
        <div class="card h-100 custom-card">
          <img class="card-img-top" src="<%= movie.poster_url %>" alt="<%= movie.title %>" style="height: 300px; object-fit: cover;">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text mb-auto"><%= movie.overview %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/movies/index.html.erb
<div class="container mt-3">
  <h1 class="mb-4">Movies</h1>
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-4 mb-3">
        <div class="card h-100">
          <%= image_tag(movie.poster_url, alt: movie.title, class: "card-img-top") if movie.poster_url.present? %>
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"><%= movie.overview %></p>
          </div>
          <div class="card-footer">
            <%= link_to 'Details', movie_path(movie), class: 'btn btn-primary btn-block' %>
            <%= link_to 'Create Bookmark', list_bookmark_path(movie), class: 'btn btn-secondary btn-block' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container mt-3">
  <h1><%= @movie.title %></h1>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag(@movie.poster_url, alt: @movie.title, class: "img-fluid") if @movie.poster_url.present? %>
    </div>
    <div class="col-md-6">
      <p><strong>Overview:</strong> <%= @movie.overview %></p>
      <p><strong>Rating:</strong> <%= @movie.rating %></p>
      
      <%= link_to 'Back to Movies', list_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>